theme: jekyll-theme-minimal
title: Matheus Lessa
description: "Hi! I'm Matheus, 1/7th of BitCake. Code bender. Audio acolyte. Creator of BitStrap. Currently working on Holodrive. Have u ever went fast?<br/><br/><a href='matheus@bitcakestudio.com'>matheus@bitcakestudio.com</a><br/><a href='https://twitter.com/matheuslrod'>twitter</a>"
