theme: jekyll-theme-minimal
title: Matheus Lessa
description: "Hi! I'm Matheus, 1/7th of [@BitCakeStudio](https://twitter.com/BitCakeStudio). Code bender. Audio acolyte. Creator of [#BitStrap](https://twitter.com/hashtag/bitstrap). Currently working on Holodrive. Have u ever went fast?"
