theme: jekyll-theme-minimal
title: Matheus Lessa
description: "Hi! I'm Matheus, 1/7th of BitCake. Code bender. Audio acolyte. Creator of BitStrap. Currently working on Holodrive. Have u ever went fast?<br/><br/>matheus@bitcakestudio.com<br/>https://twitter.com/matheuslrod"

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"
